language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t shachafotonomo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shachafotonomo/docker-react npm run test


